# Generated by Django 3.2.3 on 2021-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
